trigger:
  - main  # Run the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'
  AZURE_SUBSCRIPTION: 'terraform-pipeline'  # Use service connection name, not subscription ID

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # Step 1: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # Step 2: Authenticate with Azure and Set Terraform Authentication Variables
          - task: AzureCLI@2
            displayName: "Login to Azure using Service Connection"
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -e
                echo "Logging into Azure..."
                
                az login --identity || az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
                az account set --subscription $(AZURE_SUBSCRIPTION_ID)
                
                echo "Fetching authentication details..."
                
                export ARM_USE_OIDC=true
                export ARM_CLIENT_ID=$(AZURE_CLIENT_ID)
                export ARM_TENANT_ID=$(AZURE_TENANT_ID)
                export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)

                echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$ARM_CLIENT_ID"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$ARM_TENANT_ID"
                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$ARM_SUBSCRIPTION_ID"

                az account show

          # Step 3: Verify Terraform Authentication Variables
          - script: |
              echo "Checking if ARM environment variables are set..."
              env | grep ARM_ || echo "No ARM environment variables found."
            displayName: "Debug Terraform Authentication Variables"

          # Step 4: Initialize Terraform
          - script: |
              terraform init -upgrade \
                -backend-config="resource_group_name=$(TF_RESOURCE_GROUP)" \
                -backend-config="storage_account_name=$(TF_STORAGE_ACCOUNT)" \
                -backend-config="container_name=$(TF_CONTAINER_NAME)" \
                -backend-config="key=terraform.tfstate"
            displayName: "Terraform Init"
            workingDirectory: 'infra/terraform'

          # Step 5: Generate Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"
            workingDirectory: 'infra/terraform'

          # Step 6: Upload Terraform Lock File and Plan
          - task: PublishPipelineArtifact@1
            displayName: "Upload Terraform Lock File"
            inputs:
              targetPath: 'infra/terraform/.terraform.lock.hcl'
              artifact: 'terraform-lockfile'

          - task: PublishPipelineArtifact@1
            displayName: "Upload tfplan"
            inputs:
              targetPath: 'infra/terraform/tfplan'
              artifact: 'tfplan'

      - job: Manual_Approval
        displayName: "Approve Terraform Apply"
        dependsOn: Terraform
        pool: server
        steps:
          - task: ManualValidation@1
            displayName: "Approve Terraform Apply"
            inputs:
              notifyUsers: "jlsryn.quiambao@gmail.com"
              instructions: "Review Terraform plan before applying."

      - job: Terraform_Apply
        displayName: "Terraform Apply"
        dependsOn: Manual_Approval
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # Step 7: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # Step 8: Download Terraform Lock File and Plan
          - task: DownloadPipelineArtifact@2
            displayName: "Download Terraform Lock File"
            inputs:
              artifact: 'terraform-lockfile'
              path: 'infra/terraform'

          - task: DownloadPipelineArtifact@2
            displayName: "Download tfplan"
            inputs:
              artifact: 'tfplan'
              path: 'infra/terraform'

          # Step 9: Reinitialize Terraform
          - script: |
              terraform init -upgrade
            displayName: "Reinitialize Terraform"
            workingDirectory: 'infra/terraform'

          # Step 10: Apply Terraform Plan
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            workingDirectory: 'infra/terraform'
