trigger:
  - main

stages:
  - stage: Terraform_Dev
    displayName: "Terraform Plan for Dev"
    jobs:
      - job: Plan_Dev
        displayName: "Terraform Init & Plan"
        pool:
          vmImage: "ubuntu-22.04"
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: "latest"

          - task: AzureCLI@2
            displayName: "🔹 Login to Azure with Managed Identity"
            inputs:
              azureSubscription: "azure-terraform-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "🔹 Logging into Azure using Managed Identity..."
                az login --identity --username "$(ARM_CLIENT_ID)"
                az account set --subscription "$(ARM_SUBSCRIPTION_ID)"
                az account show
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_USE_OIDC: "true"

          - script: |
              echo "🔹 Initializing Terraform Backend..."
              terraform init -reconfigure
              terraform workspace select dev || terraform workspace new dev
              terraform plan -var="resource_group_name=dev-rg"
            displayName: "Terraform Init & Plan (Dev)"
            env:
              ARM_CLIENT_ID: "$(ARM_CLIENT_ID)"
              ARM_TENANT_ID: "$(ARM_TENANT_ID)"
              ARM_SUBSCRIPTION_ID: "$(ARM_SUBSCRIPTION_ID)"
              ARM_USE_OIDC: "true"
