trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'
  AZURE_SUBSCRIPTION: 'terraform-pipeline'
  TF_RESOURCE_GROUP: 'terraform-backend-rg'
  TF_STORAGE_ACCOUNT: 'mytfstatestoragejq0714'
  TF_CONTAINER_NAME: 'tfstate-container'

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # ✅ **Azure CLI Authentication and Blob Container Creation**
          - task: AzureCLI@2
            displayName: "Azure Login and Blob Container Creation"
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Authenticating to Azure..."
                az login --identity || echo "Already authenticated via service connection."
                az account set --subscription "$(ARM_SUBSCRIPTION_ID)"
                az account show
                echo "Creating blob container if not exists..."
                az storage container create --name $(TF_CONTAINER_NAME) --account-name $(TF_STORAGE_ACCOUNT) --auth-mode login

          # ✅ **Remove manual storage account key fetching**
          # Terraform can authenticate via Azure CLI when configured properly.
          - script: |
              terraform init -upgrade -reconfigure \
                -backend-config="resource_group_name=$(TF_RESOURCE_GROUP)" \
                -backend-config="storage_account_name=$(TF_STORAGE_ACCOUNT)" \
                -backend-config="container_name=$(TF_CONTAINER_NAME)" \
                -backend-config="key=terraform.tfstate" \
                -backend-config="use_azure_cli_auth=true"
            displayName: "Terraform Init"
            workingDirectory: 'infra/terraform'

          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"
            workingDirectory: 'infra/terraform'
