trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'
  AZURE_SUBSCRIPTION: 'terraform-pipeline'
  TF_RESOURCE_GROUP: 'terraform-backend-rg'
  TF_STORAGE_ACCOUNT: 'mytfstatestoragejq0714'
  TF_CONTAINER_NAME: 'tfstate-container'

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # Azure CLI task for login, automatically authenticates
          - task: AzureCLI@2
            displayName: "Azure Login via Service Connection"
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Successfully authenticated to Azure."
                az account show

          # Create the Blob container
          - script: |
              echo "Creating blob container if not exists..."
              az storage container create --name $(TF_CONTAINER_NAME) --account-name $(TF_STORAGE_ACCOUNT) --auth-mode login
            displayName: "Create Storage Blob Container"

          # Terraform Init (auth will be handled by the Azure Service Connection)
          - script: |
              terraform init -upgrade -reconfigure \
                -backend-config="resource_group_name=$(TF_RESOURCE_GROUP)" \
                -backend-config="storage_account_name=$(TF_STORAGE_ACCOUNT)" \
                -backend-config="container_name=$(TF_CONTAINER_NAME)" \
                -backend-config="key=terraform.tfstate"
            displayName: "Terraform Init"
            workingDirectory: 'infra/terraform'

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"
            workingDirectory: 'infra/terraform'
